### ISSUE TITLE
[feature request] post and pre apply hooks

### ISSUE THREAD

**Issue by VPraharsha03** [dahlia/dojang#19]
adding the feature to run certain scripts before or after `apply` command could make finishing up of dotfiles setup more convenient by automating the process.

**Comment by dahlia** [comment]
Thank you for the feature request! Here's a concrete design proposal for implementing hooks.

### Hook types

| Hook | When it runs |
|------|--------------|
| `pre-apply` | Before file sync (every apply) |
| `pre-first-apply` | Before file sync (first apply only) |
| `post-first-apply` | After file sync (first apply only) |
| `post-apply` | After file sync (every apply) |

"First apply" is determined by the absence of the *~/.dojang* registry file.

### Execution order

**First apply:**
```
pre-apply → pre-first-apply → file sync → post-first-apply → post-apply
```

**Subsequent applies:**
```
pre-apply → file sync → post-apply
```

### Manifest syntax

#### Simple form

```toml
[hooks]
pre-apply = ["./scripts/backup.sh"]
post-apply = ["./scripts/reload-shell.sh"]
post-first-apply = ["./scripts/install-packages.sh"]
```

#### Detailed form (with arguments and conditions)

```toml
[[hooks.post-first-apply]]
command = "brew"
args = ["bundle", "--file=Brewfile"]
moniker = "mac"

[[hooks.post-first-apply]]
command = "./scripts/install-apt-packages.sh"
args = ["--non-interactive"]
moniker = "linux"

[[hooks.post-apply]]
command = "./scripts/setup-wsl.sh"
when = "kernel-release ~ *microsoft*"
```

#### Available options

| Option | Description |
|--------|-------------|
| `command` | Executable path (required) |
| `args` | Argument array (default: `[]`) |
| `moniker` | Run only when moniker matches |
| `when` | Run only when environment predicate matches |
| `working-directory` | Working directory (default: repository root) |
| `ignore-failure` | Continue on failure (default: `false`) |

### Execution model

Commands are executed directly via subprocess (no shell involved). This avoids shell injection vulnerabilities and ensures consistent cross-platform behavior. Arguments with spaces or special characters are passed safely.

### Environment variables

The following environment variables are provided to hook scripts:

| Variable | Description |
|----------|-------------|
| `DOJANG_REPOSITORY` | Absolute path to repository |
| `DOJANG_MANIFEST` | Absolute path to manifest file |
| `DOJANG_DRY_RUN` | `true` if dry-run mode |
| `DOJANG_OS` | Current operating system |
| `DOJANG_ARCH` | Current architecture |

### Dry-run behavior

When `--dry-run` is enabled, hooks are not executed. Instead, a message like “Would run hook: *./scripts/backup.sh*” is printed.
